version: '3'
services:
  node-service:
    build: .
    container_name: node-container
    image: node-image
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000